/*
 * generated by Xtext
 */
package org.svlang.v0;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class V0RuntimeModule extends org.svlang.v0.AbstractV0RuntimeModule {

}
