/*
* generated by Xtext
*/
package org.svlang.v0;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class V0StandaloneSetup extends V0StandaloneSetupGenerated{

	public static void doSetup() {
		new V0StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

