/**
 * generated by Xtext
 */
package org.svlang.v0.validation;

import org.svlang.v0.validation.AbstractV0Validator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class V0Validator extends AbstractV0Validator {
}
