/*
 * generated by Xtext
 */
package org.svlang.v0.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.svlang.v0.ui.internal.V0Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class V0ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return V0Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return V0Activator.getInstance().getInjector(V0Activator.ORG_SVLANG_V0_V0);
	}
	
}
