/**
 * generated by Xtext
 */
package org.svlang.v0.ui.contentassist;

import org.svlang.v0.ui.contentassist.AbstractV0ProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class V0ProposalProvider extends AbstractV0ProposalProvider {
}
