/*
* generated by Xtext
*/
package org.svlang.v0;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class V0UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.svlang.v0.ui.internal.V0Activator.getInstance().getInjector("org.svlang.v0.V0");
	}
	
}
