/*
* generated by Xtext
*/
package org.svlang.v0.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.svlang.v0.services.V0GrammarAccess;

public class V0Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private V0GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.svlang.v0.parser.antlr.internal.InternalV0Parser createParser(XtextTokenStream stream) {
		return new org.svlang.v0.parser.antlr.internal.InternalV0Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}
	
	public V0GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(V0GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
