/*
 * generated by Xtext
 */
package org.example.domainmodel.ui.contentassist

import org.example.domainmodel.ui.contentassist.AbstractDomainmodelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DomainmodelProposalProvider extends AbstractDomainmodelProposalProvider {
}
