/*
 * generated by Xtext
 */
package org.svlang.v0.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class V0UiModule extends org.svlang.v0.ui.AbstractV0UiModule {
	public V0UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
