package SVLang.v0.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {


  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new CodeFile_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Codeline_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Fun_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Import_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Main_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Namespace_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }



  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"SVLang.v0.structure.CodeFile", "SVLang.v0.structure.Codeline", "SVLang.v0.structure.Fun", "SVLang.v0.structure.Import", "SVLang.v0.structure.Main", "SVLang.v0.structure.Namespace"};
}
