/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterators;
import java.util.Iterator;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.Greeting;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class MyDslGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterator<Greeting> _filter = Iterators.<Greeting>filter(_allContents, Greeting.class);
    final Function1<Greeting, String> _function = new Function1<Greeting, String>() {
      public String apply(final Greeting it) {
        return it.getName();
      }
    };
    Iterator<String> _map = IteratorExtensions.<Greeting, String>map(_filter, _function);
    final String names = IteratorExtensions.join(_map, " and ");
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class Main {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"Greetings ");
    String _plus = (_builder.toString() + names);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("!\");");
    _builder_1.newLine();
    _builder_1.append("\t\t\t\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("}");
    _builder_1.newLine();
    String _plus_1 = (_plus + _builder_1);
    fsa.generateFile("Main.java", _plus_1);
  }
}
