package SVLang.v0.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new CodeFile_BehaviorDescriptor();
      case 3:
        return new Import_BehaviorDescriptor();
      case 5:
        return new Namespace_BehaviorDescriptor();
      case 4:
        return new Main_BehaviorDescriptor();
      case 1:
        return new Codeline_BehaviorDescriptor();
      case 2:
        return new Fun_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"SVLang.v0.structure.CodeFile", "SVLang.v0.structure.Codeline", "SVLang.v0.structure.Fun", "SVLang.v0.structure.Import", "SVLang.v0.structure.Main", "SVLang.v0.structure.Namespace"};
}
