package SVLang.v0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Codeline_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Codeline_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SVLang.v0.structure.Codeline";
  }
}
