package SVLang.v0.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Namespace_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Namespace_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "SVLang.v0.structure.Namespace";
  }
}
